# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ar2rO - From hobbyist developer to job ready in X months - 100DaysOfCode
email: arturo@ar2.ro
description: > # this means to ignore newlines until "baseurl:"
  I'm a hobbyist developer pursuing a carrer change at 32yo. 
  I'll start by relearning the fundamentals of HTML, CSS, JavaScript and moving to more advanced topics afterwards in the hope of landing a developer job.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ar2.ro" # the base hostname & protocol for your site
collections:
  annotations:
    output: true
# Build settings
markdown: kramdown
